DIVE-2　マイグレーション・モデルファイル作成
tomonaganoriaki/Laravel__Training__DivingApp pull request #2
Opened 2023-11-09 13:21 UTC by tomonaganoriaki

### Notion URL

https://www.notion.so/cf6573ac11984472afbc1113854efe8c

### タスク内容

[DB設計書](https://www.notion.so/b2ae4a04bc014273aaaf65cd5223fbd8?v=6c180a87bf6147cab9abc4853d7dd1c3)を基にマイグレーションファイルとモデルファイルを作成し、実行。

### やったこと

[DB設計書](https://www.notion.so/b2ae4a04bc014273aaaf65cd5223fbd8?v=6c180a87bf6147cab9abc4853d7dd1c3)を基にマイグレーションファイルとモデルファイルを作成し、実行。

### 動作確認

- Sequel Aceにて、設計通りにテーブルが出来ていることを確認。
- Modelに関しては他タスクで必要に応じて修正予定。

### 備考

なし。

2023-11-09 23:33 UTC, igarashitakukmi requested changes
細かいところですが、
実際の開発の水準でバシバシ指摘していくので、認識お願いします！

2023-11-09 23:33 UTC, igarashitakukmi commented on app/Models/Address.php
use SoftDelete
が抜けていると思います！
※他もチェックお願いします

2023-11-09 23:33 UTC, igarashitakukmi commented on app/Models/Address.php
> +    }
![badge](https://img.shields.io/badge/review-nits-green.svg)
細かいですが、適切な位置で改行はさみましょう！

```suggestion
    use HasFactory;

    public $timestamps = true;
    protected $table = 'addresses';
    protected $primaryKey = 'id';
    protected $fillable = [
        'id',
        'postal_code',
        'prefecture',
        'city',
        'street'
    ];

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function orders(): BelongsToMany
    {
        return $this->belongsToMany(Order::class);
    }
```

2023-11-09 23:33 UTC, igarashitakukmi commented on app/Models/Address.php
> +    protected $fillable = [
![badge](https://img.shields.io/badge/review-suggestion-blue.svg)
guardedのほうがメンテナンスが楽です!
https://qiita.com/toro_ponz/items/b33c757cb7ba5bb48ed4
※他も確認お願いします

```suggestion
    protected $guarded = ['id'];
```

2023-11-09 23:33 UTC, igarashitakukmi commented on app/Models/Address.php
> +    public function user()
![badge](https://img.shields.io/badge/review-suggestion-blue.svg)
返り値のタイプヒント書きましょう！
※他も確認お願いします
```suggestion
    public function user() BelongsTo
```

2023-11-09 23:33 UTC, igarashitakukmi commented on database/migrations/2023_11_08_203628_create_addresses_table.php
> +            $table->string('street')->nullable(false);
![badge](https://img.shields.io/badge/review-nits-green.svg)
デフォルトでnullable(false)なので、書かなくて良いです！
※他も確認お願いします

```suggestion
            $table->string('postal_code');
            $table->string('prefecture');
            $table->string('city');
            $table->string('street');
```

2023-11-09 23:33 UTC, igarashitakukmi commented on app/Models/Order.php
![badge](https://img.shields.io/badge/review-suggestion-blue.svg)
日付系のカラムはcastしましょう！
※https://readouble.com/laravel/9.x/ja/eloquent-mutators.html 属性のキャスト参照

```
protected $casts = [
    'order_date' => 'datetime',
    'shipped_date' => 'datetime',
];
```

こうすることで、日付系のカラムをCarbonインスタンスとして扱うことが出来ます。
（Carbon::parseを挟む必要がない）

例）日付をフォーマットしたい時
■castなし
Carbon::parse($order->order_date)->format('Y-m-d');

■castあり
$order->order_date->format('Y-m-d');

2023-11-09 23:36 UTC, igarashitakukmi commented on app/Models/Order.php
日付系だけではなく、boolean系もcastをお願いします！（0,1のフラグで管理するもの）

2023-11-10 06:58 UTC, tomonaganoriaki commented
@igarashitakukmi 
全て修正完了済みです！

2023-11-10 23:38 UTC, igarashitakukmi approved these changes
LGTM！

2023-11-10 23:38 UTC, merged