DIVE-3　Admin（管理者）アカウント管理機能の実装
tomonaganoriaki/Laravel__Training__DivingApp pull request #4
Opened 2023-11-11 15:34 UTC by tomonaganoriaki

### Notion URL

https://www.notion.so/Admin-Admin-1d15eb1ab6a64995b87d272ce2f5f3e5

### タスク内容

Adminアカウントの作成・一覧・更新・削除
全て実装する。

### やったこと

- AdminAccountControllerを作成＋作成・一覧・更新・削除メソッドを定義
- ブレード「作成・一覧・更新・削除」を作成
- スタイル調整

### 動作確認

- 要件全て実装済み。（下記画像参照）

▼ アドミン一覧

> 現状登録されている管理者アカウントがリストとして全て表示される。
> 新規作成・編集・削除ボタンを設置し、クリックすると下記3機能画面へ推移する。

![Laravel (2)](https://github.com/tomonaganoriaki/Laravel__Training__DivingApp/assets/115410371/17029f96-6e90-4cc9-9d09-75940152d1c0)

▼ アドミン作成

> 管理者アカウントの新規作成が可能。
> SQLへの反映＋作成したアカウントでログインできるかまで動作確認済。

![Laravel (2)3](https://github.com/tomonaganoriaki/Laravel__Training__DivingApp/assets/115410371/f0a0a46a-7e39-401c-afc2-67589d9c8de8)

▼ アドミン更新

> 管理者アカウントの新規作成が可能。
> SQLへの反映＋編集したアカウントでログインできるかまで動作確認済。

![Laravel (2)56](https://github.com/tomonaganoriaki/Laravel__Training__DivingApp/assets/115410371/c6834937-bf8b-43ed-9912-269607d38e67)

▼ アドミン削除

> 削除ボタンを押すと確認アラートが表示され、OKを押すと削除される。
> 削除は論理削除で、DB（deleted_at）への反映も確認済。

![スクリーンショット 0005-11-12 0 27 34（4）](https://github.com/tomonaganoriaki/Laravel__Training__DivingApp/assets/115410371/aeb7289f-83c2-429b-a50a-1d4fced16da9)

### 備考

特になし。

2023-11-12 23:17 UTC, igarashitakukmi requested changes

2023-11-12 23:17 UTC, igarashitakukmi commented on app/Http/Controllers/Admin/AdminAccountController.php
> +            'email' => strtolower($request->email),
[ask]
大文字のメールアドレスも存在すると思うので、
勝手に小文字に変換されたらユーザーの意図しない動作になりそうだなと思ったのですが、必要ですかね？？
不要であれば削除お願いします！

2023-11-13 06:04 UTC, tomonaganoriaki commented on app/Http/Controllers/Admin/AdminAccountController.php
> +            'email' => strtolower($request->email),
@igarashitakukmi 
ご指摘の通り大文字の場合もあるため、strtolowerメソッドを削除しました！

2023-11-13 08:15 UTC, igarashitakukmi approved these changes

2023-11-13 08:15 UTC, merged