DIVE-4and5　カテゴリ・タグ管理機能の実装
tomonaganoriaki/Laravel__Training__DivingApp pull request #5
Opened 2023-11-13 14:57 UTC by tomonaganoriaki

### Notion URL

https://www.notion.so/add7f79d10584e5b95cbf5959c483473?v=e1cbafc470784592af60610745363380

### タスク内容

- [DIVE-4](https://www.notion.so/Admin-cae77328219b44c3bb466d0669e8fd43)：カテゴリ管理機能の実装
- [DIVE-5](https://www.notion.so/Admin-d2c15c2bc7d44b4aba4a68ee399d2fa1)：タグ管理機能の実装

### やったこと

タスク[DIVE-3](https://github.com/tomonaganoriaki/Laravel__Training__DivingApp/pull/4)と同様、「コントローラ」「ルート」「ブレード」を其々作成し、カテゴリ＆タグ管理（作成・編集・削除）機能を実装。

### 動作確認

▼ 一覧画面
![Laravel (2)](https://github.com/tomonaganoriaki/Laravel__Training__DivingApp/assets/115410371/af0d0e00-3c10-45dd-a1ee-ef13f5dcf342)
![Laravel (2)のコピー](https://github.com/tomonaganoriaki/Laravel__Training__DivingApp/assets/115410371/7d841af0-a0d4-45e8-8dbd-9089ba9b35ca)

▼ 作成画面
![Laravel (2)三](https://github.com/tomonaganoriaki/Laravel__Training__DivingApp/assets/115410371/349af9a9-f361-47e1-a956-15cc175d9d2a)
![Laravel (2)5](https://github.com/tomonaganoriaki/Laravel__Training__DivingApp/assets/115410371/e52364ed-3f47-462f-bae5-32cda2d1fba6)

▼ 編集画面
![Laravel (2)12](https://github.com/tomonaganoriaki/Laravel__Training__DivingApp/assets/115410371/4e73a9a2-df88-404e-bbcc-fa33a0a56e12)
![Laravel (2)233](https://github.com/tomonaganoriaki/Laravel__Training__DivingApp/assets/115410371/bb3c112b-1988-4970-9766-6b6fcbc33f70)

▼ 削除画面
![スクリーンショット 0005-11-13 23 56 14（3）](https://github.com/tomonaganoriaki/Laravel__Training__DivingApp/assets/115410371/b53d3670-dfec-470d-876f-67390734312f)

※ [DIVE-3](https://github.com/tomonaganoriaki/Laravel__Training__DivingApp/pull/4)と類似処理のため詳細説明は省略。

### 備考

スケジュールの都合で[DIVE-4](https://www.notion.so/Admin-cae77328219b44c3bb466d0669e8fd43)と[DIVE-5](https://www.notion.so/Admin-d2c15c2bc7d44b4aba4a68ee399d2fa1)を同ブランチにて実装しております。

2023-11-13 22:51 UTC, igarashitakukmi requested changes
動作的には大丈夫だと思います。
他、CXCの規約基準でレビューしてます。確認お願いします！

2023-11-13 22:51 UTC, igarashitakukmi commented on app/Http/Controllers/Admin/CategoryController.php
> +use App\Models\Category;
![badge](https://img.shields.io/badge/review-nits-green.svg)
use の順番はアルファベット順でお願いします！
```suggestion
use App\Http\Controllers\Controller;
use App\Models\Category;
use Illuminate\Http\Request;
```

2023-11-13 22:51 UTC, igarashitakukmi commented on routes/admin.php
> +    Route::delete('/category/{id}', [CategoryController::class, 'destroy'])->name('category.destroy');
![badge](https://img.shields.io/badge/review-suggestion-blue.svg)
パスパラメータはルーティング段階で入りうる値を制御しましょう！
```suggestion
    Route::get('/category/{id}/edit', [CategoryController::class, 'edit'])->name('category.edit')->where('id', '[0-9]+');
    Route::post('/category/{id}', [CategoryController::class, 'update'])->name('category.update')->where('id', '[0-9]+');
    Route::delete('/category/{id}', [CategoryController::class, 'destroy'])->name('category.destroy')->where('id', '[0-9]+');
```

2023-11-13 22:51 UTC, igarashitakukmi commented on app/Http/Controllers/Admin/TagController.php
> +    }
![badge](https://img.shields.io/badge/review-suggestion-blue.svg)
メソッドの引数と返り値には基本的に型指定をしましょう！

```suggestion
    use Illuminate\View\View;
    ...
    public function edit(int $id): View
    {
        $tag = Tag::findOrFail($id);
        return view('admin.tag.edit')->with('tag', $tag);
    }
```

2023-11-14 10:15 UTC, tomonaganoriaki commented
@igarashitakukmi 
諸々修正完了しました！

2023-11-14 13:26 UTC, merged