DIVE-9　商品管理機能の実装
tomonaganoriaki/Laravel__Training__DivingApp pull request #7
Opened 2023-11-19 06:27 UTC by tomonaganoriaki

### Notion URL

https://www.notion.so/Admin-da2dc83b09644a96b7975be16bb39118

### タスク内容

- 商品管理（新規作成・編集・削除）機能を実装。

### やったこと

- 商品管理（新規作成・編集・削除）機能を実装。
- 商品管理項目は「商品名」「商品説明」「価格」「在庫数」「カテゴリ」「タグ」「商品画像」の7項目。
- 当機能に[OKR](https://docs.google.com/spreadsheets/d/1VvKqX3gNLXma9OwmL6aht3zQzsufi36SN_6Ey1P3MZ8/edit#gid=1771909684)にある「検索機能」を子機能として実装。
- 当機能に[OKR](https://docs.google.com/spreadsheets/d/1VvKqX3gNLXma9OwmL6aht3zQzsufi36SN_6Ey1P3MZ8/edit#gid=1771909684)にある「CSVインポート・エクスポート機能」を子機能として実装。

### 本タスクで達成したOKR（[朝長_人事評価シート](https://docs.google.com/spreadsheets/d/1SDb2ifKe5BuGJcB2FpU1bf0yQIM38v4Y77KHWuiL1SQ/edit#gid=1162632193)）

1. CSVインポートを有したプロダクトを実装
2. 検索機能を有したプロダクトを実装

### 動作確認『メイン』

商品管理（新規作成・編集・削除）が出来る。
![dive_app](https://github.com/tomonaganoriaki/Laravel__Training__DivingApp/assets/115410371/2196a7fc-fa18-4333-8098-bbdd54ad0e78)
※ 詳細説明は今までの[PR](https://github.com/tomonaganoriaki/Laravel__Training__DivingApp/pull/6)と同等のため省略。

### 動作確認『OKR：検索機能』

商品を「キーワード部分一致」「料金レンジ」「カテゴリー」で検索できるかを確認。
条件を組み合わせたうえでの検索も出来ることを確認

▼ 通常時
![Laravel (1)](https://github.com/tomonaganoriaki/Laravel__Training__DivingApp/assets/115410371/bf417439-e398-44b8-9970-f84f668e1af6)

▼ 条件「部分一致：かき」「カテゴリー：2」で検索
![Laravel (2)](https://github.com/tomonaganoriaki/Laravel__Training__DivingApp/assets/115410371/57a01f33-015f-4c35-ae97-4247612843bd)

### 動作確認『OKR：CSVインポート・エクスポート機能』

▼ 下記手順によって動作する。
![Laravel (1) 2](https://github.com/tomonaganoriaki/Laravel__Training__DivingApp/assets/115410371/bf5b55cf-91d7-46d8-a3da-e8625e707120)

▼ 出力したファイルを編集のうえインポートすると、商品情報は更新される。
![スクリーンショット 0005-11-19 15 24 27](https://github.com/tomonaganoriaki/Laravel__Training__DivingApp/assets/115410371/0e2d1ead-c1dd-435e-be9d-7c979b13945c)

### 備考

@igarashitakukmi 
OKR機能重視でご確認よろしくお願いいたします！

2023-11-19 23:08 UTC, igarashitakukmi requested changes

2023-11-19 23:08 UTC, igarashitakukmi commented on app/Http/Controllers/Admin/ProductController.php
> +            ]);
![badge](https://img.shields.io/badge/review-must-red.svg)
バリデーションはトランザクションの外に出しましょう！トランザクションは基本的にDBデータの整合性を保てれば良いので、バリデーションを含める必要はないです。

2023-11-19 23:08 UTC, igarashitakukmi commented on app/Http/Controllers/Admin/ProductController.php
> +            }
![badge](https://img.shields.io/badge/review-must-red.svg)
データの作成に失敗すれば、自然と例外がcatchされて、#92~のロールバックが走るので、これらは不要です！
```suggestion
```

2023-11-19 23:08 UTC, igarashitakukmi commented on app/Http/Controllers/Admin/ProductController.php
> +            return redirect()->route('admin.product.index');
![badge](https://img.shields.io/badge/review-suggestion-blue.svg)
例外をキャッチした場合はログを吐いておきましょう。
```suggestion
            } catch (\Exception $e) {
                DB::rollBack();
                \Log::error($e->getMessage());
                session()->flash('flash_message', '商品の作成に失敗しました。');
                return redirect()->route('admin.product.index');
```

2023-11-19 23:08 UTC, igarashitakukmi commented on app/Http/Controllers/Admin/ProductController.php
> +                }
```suggestion
```

2023-11-19 23:08 UTC, igarashitakukmi commented on app/Http/Controllers/Admin/ProductController.php
> +            }
```suggestion
```

2023-11-19 23:08 UTC, igarashitakukmi commented on app/Http/Controllers/Admin/ProductController.php
> +    public function destroy($id): RedirectResponse
![badge](https://img.shields.io/badge/review-nits-green.svg)
タイプヒントお願いします。
```suggestion
    public function destroy(int $id): RedirectResponse
```

2023-11-19 23:08 UTC, igarashitakukmi commented on app/Http/Controllers/Admin/ProductController.php
> +            $product->save();
![badge](https://img.shields.io/badge/review-suggestion-blue.svg)
csvもフォーマットバリデーションも必要かと思います！
例えばカテゴリーはカンマ区切りが前提になっていたり、商品名は文字数制限が合ったり。

2023-11-20 04:04 UTC, tomonaganoriaki commented on app/Http/Controllers/Admin/ProductController.php
> +    {
修正済

2023-11-20 04:14 UTC, tomonaganoriaki commented on app/Http/Controllers/Admin/ProductController.php
> +    $selectCategory = request()->input('category');
修正済

2023-11-20 04:18 UTC, tomonaganoriaki commented on app/Http/Controllers/Admin/ProductController.php
> +        return view('admin.product.create')->with('tags', $tags)->with('categories', $categories);
修正済

2023-11-20 04:20 UTC, tomonaganoriaki commented on app/Http/Controllers/Admin/ProductController.php
> +            ]);
修正済

2023-11-20 04:29 UTC, tomonaganoriaki commented on app/Http/Controllers/Admin/ProductController.php
> +            }
修正済

2023-11-20 04:31 UTC, tomonaganoriaki commented on app/Http/Controllers/Admin/ProductController.php
> +            return redirect()->route('admin.product.index');
修正済

2023-11-20 04:33 UTC, tomonaganoriaki commented on app/Http/Controllers/Admin/ProductController.php
> +    public function destroy($id): RedirectResponse
修正済

2023-11-20 04:41 UTC, tomonaganoriaki commented on app/Http/Controllers/Admin/ProductController.php
> +            $product->save();
修正済

2023-11-20 14:39 UTC, tomonaganoriaki commented
@igarashitakukmi 
全て修正済です！

2023-11-24 09:41 UTC, igarashitakukmi requested changes

2023-11-27 00:32 UTC, tomonaganoriaki commented on app/Http/Controllers/Admin/ProductController.php
> +            ]);
修正済

2023-11-27 00:36 UTC, tomonaganoriaki commented on app/Http/Controllers/Admin/ProductController.php
> +            \Log::error($e->getMessage());
修正済

2023-11-27 00:45 UTC, tomonaganoriaki commented
@igarashitakukmi 
全て修正完了しました！

2023-11-27 23:30 UTC, igarashitakukmi requested changes
追加追加ですみませんが、お願いします！

2023-11-27 23:30 UTC, igarashitakukmi commented on app/Http/Controllers/Admin/ProductController.php
> +                ]);
![badge](https://img.shields.io/badge/review-ask-blue.svg)
Validatorインスタンスが生成されていますが、
生成したインスタンス（`$validator`）が以降どこにも使われていないため、バリデーションが機能していない気がします。

確認お願いします！

2023-11-27 23:30 UTC, igarashitakukmi commented on app/Http/Controllers/Admin/ProductController.php
> +                $product->tags()->sync($tagIds);
![badge](https://img.shields.io/badge/review-must-red.svg)
CSVの行データをループで回して、
その中でSQL（Eloquent）を実行していますが、ループの中でのSQL実行は基本的にNGです。
（SQLはDBに接続する分、通常のPHP処理よりも処理が重いため、なるべく実行回数を少なくしたい）

なのでまずはバリデーションの処理を通してから、
DBに挿入用、更新用のデータを変数に格納し、
その変数を使ってバルクインサートorアップデートをする形が理想です！

2023-11-29 10:36 UTC, tomonaganoriaki commented on app/Http/Controllers/Admin/ProductController.php
> +                ]);
修正済みです！

2024-01-19 10:22 UTC, closed without merging